name: python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  python-lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: isort
        if: '!cancelled()'
        run: poetry run isort . --check
      - name: black
        if: '!cancelled()'
        run: poetry run black . --check --verbose
      - name: flake8
        if: '!cancelled()'
        run: poetry run flake8 . --count --show-source --statistics
      - name: Test with pytest
        if: '!cancelled()'
        run: |
          poetry run pytest
